//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int Id { get; set; }
        public int 语文Id { get; set; }
        public int 程序开发Id { get; set; }
        public int 计算机文化基础Id { get; set; }
        public int asp动态网页设计Id { get; set; }
        public int 英语Id { get; set; }
    }
}
